-- Generated by Oracle SQL Developer Data Modeler 21.2.0.165.1515
--   at:        2021-12-10 20:45:05 CET
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE autorzy_gry (
    imiê     VARCHAR2(20 CHAR) NOT NULL,
    nazwisko VARCHAR2(30 CHAR) NOT NULL
);

ALTER TABLE autorzy_gry ADD CONSTRAINT autorzy_gry_pk PRIMARY KEY ( imiê,
                                                                    nazwisko );

CREATE TABLE cz³onkowie_klubu (
    cz³onek_id      NUMBER NOT NULL,
    rola            VARCHAR2(30 CHAR) NOT NULL,
    data_do³¹czenia DATE NOT NULL,
    kluby_nazwa     VARCHAR2(50 CHAR) NOT NULL,
    gracze_imiê     VARCHAR2(20 CHAR) NOT NULL,
    gracze_nazwisko VARCHAR2(30 CHAR) NOT NULL
);

ALTER TABLE cz³onkowie_klubu ADD CONSTRAINT cz³onek_pk PRIMARY KEY ( cz³onek_id );


--  ERROR: UK name length exceeds maximum allowed length(30) 
ALTER TABLE cz³onkowie_klubu ADD CONSTRAINT id_cz³onka_klubu UNIQUE ( gracze_imiê,
                                                                                                     gracze_nazwisko );

CREATE TABLE dodatki (
    podtytu³  VARCHAR2(30 CHAR) NOT NULL,
    gry_tytu³ VARCHAR2(30 CHAR) NOT NULL
);

ALTER TABLE dodatki ADD CONSTRAINT dodatki_pk PRIMARY KEY ( podtytu³,
                                                            gry_tytu³ );

CREATE TABLE gracz_gry_oceny (
    ocena           INTEGER NOT NULL,
    gry_tytu³       VARCHAR2(30 CHAR) NOT NULL,
    gracze_imiê     VARCHAR2(20 CHAR)
--  ERROR: VARCHAR2 size not specified 
     NOT NULL,
    gracze_nazwisko VARCHAR2(30 CHAR)
--  ERROR: VARCHAR2 size not specified 
     NOT NULL,
    gracze_gracz_id NUMBER NOT NULL
);

ALTER TABLE gracz_gry_oceny
    ADD CONSTRAINT gracz_gry_oceny_pk PRIMARY KEY ( ocena,
                                                    gracze_imiê,
                                                    gracze_nazwisko,
                                                    gry_tytu³ );

CREATE TABLE gracze (
    gracz_id NUMBER NOT NULL,
    imiê     VARCHAR2(20 CHAR) NOT NULL,
    nazwisko VARCHAR2(30 CHAR) NOT NULL
);

ALTER TABLE gracze ADD CONSTRAINT gracz_pk PRIMARY KEY ( gracz_id );

ALTER TABLE gracze ADD CONSTRAINT gracze_imiê_nazwisko_un UNIQUE ( imiê,
                                                                   nazwisko );

CREATE TABLE gry (
    tytu³                VARCHAR2(30 CHAR) NOT NULL,
    autorzy_gry_imiê     VARCHAR2(20 CHAR) NOT NULL,
    autorzy_gry_nazwisko VARCHAR2(30 CHAR) NOT NULL,
    typy_gry_gatunek     VARCHAR2(20 CHAR) NOT NULL
);

ALTER TABLE gry ADD CONSTRAINT gry_pk PRIMARY KEY ( tytu³ );

CREATE TABLE kluby (
    klub_id NUMBER NOT NULL,
    nazwa   VARCHAR2(50 CHAR) NOT NULL
);

ALTER TABLE kluby ADD CONSTRAINT klub_pk PRIMARY KEY ( klub_id );

ALTER TABLE kluby ADD CONSTRAINT kluby_nazwa_un UNIQUE ( nazwa );

CREATE TABLE lokalizacje (
    miasto VARCHAR2(30 CHAR) NOT NULL,
    obiekt VARCHAR2(30 CHAR) NOT NULL
);

ALTER TABLE lokalizacje ADD CONSTRAINT lokalizacje_pk PRIMARY KEY ( miasto,
                                                                    obiekt );

CREATE TABLE patroni_medialni (
    nazwa VARCHAR2(50 CHAR) NOT NULL
);

ALTER TABLE patroni_medialni ADD CONSTRAINT patroni_medialni_pk PRIMARY KEY ( nazwa );

CREATE TABLE patroni_wydarzenia (
    wydarzenia_nazwa       VARCHAR2(30 CHAR) NOT NULL,
    patroni_medialni_nazwa VARCHAR2(50 CHAR) NOT NULL
);

ALTER TABLE patroni_wydarzenia ADD CONSTRAINT patroni_wydarzeñ PRIMARY KEY ( wydarzenia_nazwa,
                                                                             patroni_medialni_nazwa );

CREATE TABLE rozgrywka_gracze_role (
    rola                                      VARCHAR2(30 CHAR) NOT NULL,
    nazwa                                     VARCHAR2(30 CHAR) NOT NULL,
    imie_gracza              VARCHAR2(20 CHAR)
--  ERROR: VARCHAR2 size not specified 
     NOT NULL, 
--  ERROR: Column name length exceeds maximum allowed length(30) 
    nazwisko_gracza          VARCHAR2(30 CHAR)
--  ERROR: VARCHAR2 size not specified 
     NOT NULL,
    nazwa1                                    VARCHAR2(50 CHAR) NOT NULL,
    nazwa2                                    VARCHAR2(50 CHAR) NOT NULL,
    data                                      DATE NOT NULL, 
--  ERROR: Column name length exceeds maximum allowed length(30) 
    id_rozgrywki_turniejowej NUMBER NOT NULL,
    nazwa3                                    VARCHAR2(30 CHAR)
--  ERROR: VARCHAR2 size not specified 
     NOT NULL,
    cz³onkowie_klubu_cz³onek_id               NUMBER NOT NULL
);

ALTER TABLE rozgrywka_gracze_role
    ADD CONSTRAINT rozgrywka_gracze_role_pk PRIMARY KEY ( nazwa,
                                                          nazwa1,
                                                          nazwa2,
                                                          data,
                                                          rola,
                                                          imie_gracza,
                                                          nazwisko_gracza );

CREATE TABLE rozgrywki (
    rozgrywka_id       NUMBER NOT NULL,
    data               DATE NOT NULL,
    wygrywaj¹cy_gracz  CHAR(50 CHAR),
    gry_tytu³          VARCHAR2(30 CHAR) NOT NULL,
    gracze_imiê        VARCHAR2(20 CHAR)
--  ERROR: VARCHAR2 size not specified 
     NOT NULL,
    gracze_nazwisko    VARCHAR2 (30 CHAR)
--  ERROR: VARCHAR2 size not specified 
     NOT NULL,
    gracze_imiê1       VARCHAR2(20 CHAR)
--  ERROR: VARCHAR2 size not specified 
     NOT NULL,
    gracze_nazwisko1   VARCHAR2(30 CHAR)
--  ERROR: VARCHAR2 size not specified 
     NOT NULL,
    lokalizacje_miasto VARCHAR2(30 CHAR) NOT NULL,
    lokalizacje_obiekt VARCHAR2(30 CHAR) NOT NULL,
    gracze_gracz_id    NUMBER NOT NULL,
    gracze_gracz_id1   NUMBER NOT NULL
);

ALTER TABLE rozgrywki ADD CONSTRAINT rozgrywka_pk PRIMARY KEY ( rozgrywka_id );


--  ERROR: UK name length exceeds maximum allowed length(30) 
ALTER TABLE rozgrywki
    ADD CONSTRAINT id_rozgrywki UNIQUE ( gry_tytu³,
                                                                                                                  gracze_imiê1,
                                                                                                                  gracze_nazwisko1,
                                                                                                                  gracze_imiê,
                                                                                                                  gracze_nazwisko,
                                                                                                                  data );

CREATE TABLE rozgrywki_turniejowe (
    rozgrywka_turniej_id NUMBER NOT NULL,
    data                 DATE NOT NULL,
    wygrywaj¹cy_klub     VARCHAR2(50 CHAR),
    kluby_nazwa          VARCHAR2(50 CHAR) NOT NULL,
    kluby_nazwa1         VARCHAR2(50 CHAR) NOT NULL,
    turnieje_nazwa       VARCHAR2(30 CHAR) NOT NULL,
    kluby_klub_id        NUMBER NOT NULL,
    kluby_klub_id1       NUMBER NOT NULL
);

ALTER TABLE rozgrywki_turniejowe ADD CONSTRAINT rozgrywka_turniej_pk PRIMARY KEY ( rozgrywka_turniej_id );


--  ERROR: UK name length exceeds maximum allowed length(30) 
ALTER TABLE rozgrywki_turniejowe
    ADD CONSTRAINT id_rozgrywki_turniejowej UNIQUE ( turnieje_nazwa,
                                                                                                 kluby_nazwa,
                                                                                                 kluby_nazwa1,
                                                                                                 data );

CREATE TABLE turnieje (
    nazwa              VARCHAR2(30 CHAR) NOT NULL,
    wydarzenia_nazwa   VARCHAR2(30 CHAR) NOT NULL,
    lokalizacje_miasto VARCHAR2(30 CHAR) NOT NULL,
    lokalizacje_obiekt VARCHAR2(30 CHAR) NOT NULL
);

ALTER TABLE turnieje ADD CONSTRAINT turnieje_pk PRIMARY KEY ( nazwa );

CREATE TABLE typy_gry (
    gatunek           VARCHAR2(20 CHAR) NOT NULL,
    gatunek_dodatkowy VARCHAR2(20 CHAR)
);

ALTER TABLE typy_gry ADD CONSTRAINT typy_gry_pk PRIMARY KEY ( gatunek );

CREATE TABLE w³aœciciele_gry (
    gracze_imiê     VARCHAR2(20 CHAR),
    gracze_nazwisko VARCHAR2(30 CHAR),
    kluby_nazwa     VARCHAR2(50 CHAR),
    gry_tytu³       VARCHAR2(30 CHAR) NOT NULL,
    koszt_zakupu    FLOAT
);

ALTER TABLE w³aœciciele_gry
    ADD CONSTRAINT arc_1 CHECK ( ( ( gracze_imiê IS NOT NULL )
                                   AND ( gracze_nazwisko IS NOT NULL )
                                   AND ( kluby_nazwa IS NULL ) )
                                 OR ( ( kluby_nazwa IS NOT NULL )
                                      AND ( gracze_imiê IS NULL )
                                      AND ( gracze_nazwisko IS NULL ) ) );

ALTER TABLE w³aœciciele_gry ADD CONSTRAINT w³aœciciele_gry_pk PRIMARY KEY ( gry_tytu³ );

CREATE TABLE wydarzenia (
    nazwa       VARCHAR2(30 CHAR) NOT NULL,
    organizator VARCHAR2(50 CHAR) NOT NULL
);

ALTER TABLE wydarzenia ADD CONSTRAINT wydarzenia_pk PRIMARY KEY ( nazwa );

ALTER TABLE cz³onkowie_klubu
    ADD CONSTRAINT cz³onkowie_klubu_gracze_fk FOREIGN KEY ( gracze_imiê,
                                                            gracze_nazwisko )
        REFERENCES gracze ( imiê,
                            nazwisko );

ALTER TABLE cz³onkowie_klubu
    ADD CONSTRAINT cz³onkowie_klubu_kluby_fk FOREIGN KEY ( kluby_nazwa )
        REFERENCES kluby ( nazwa );

ALTER TABLE dodatki
    ADD CONSTRAINT dodatki_gry_fk FOREIGN KEY ( gry_tytu³ )
        REFERENCES gry ( tytu³ );

ALTER TABLE gracz_gry_oceny
    ADD CONSTRAINT gracz_gry_oceny_gracze_fk FOREIGN KEY ( gracze_gracz_id )
        REFERENCES gracze (gracz_id );

ALTER TABLE gracz_gry_oceny
    ADD CONSTRAINT gracz_gry_oceny_gry_fk FOREIGN KEY ( gry_tytu³ )
        REFERENCES gry ( tytu³ );

ALTER TABLE gry
    ADD CONSTRAINT gry_autorzy_gry_fk FOREIGN KEY ( autorzy_gry_imiê,
                                                    autorzy_gry_nazwisko )
        REFERENCES autorzy_gry ( imiê,
                                 nazwisko );

ALTER TABLE gry
    ADD CONSTRAINT gry_typy_gry_fk FOREIGN KEY ( typy_gry_gatunek )
        REFERENCES typy_gry ( gatunek );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE patroni_wydarzenia
    ADD CONSTRAINT id_patrona_fk FOREIGN KEY ( patroni_medialni_nazwa )
        REFERENCES patroni_medialni ( nazwa );

ALTER TABLE patroni_wydarzenia
    ADD CONSTRAINT patroni_wydarzeñ_wydarzenia_fk FOREIGN KEY ( wydarzenia_nazwa )
        REFERENCES wydarzenia ( nazwa );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE rozgrywka_gracze_role
    ADD CONSTRAINT id_roli_gracza_fk FOREIGN KEY ( cz³onkowie_klubu_cz³onek_id )
        REFERENCES cz³onkowie_klubu ( cz³onek_id );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE rozgrywka_gracze_role
    ADD CONSTRAINT id_rola_rozgrywka_fk FOREIGN KEY ( id_rozgrywki_turniejowej )
        REFERENCES rozgrywki_turniejowe ( rozgrywka_turniej_id );

ALTER TABLE rozgrywki
    ADD CONSTRAINT rozgrywki_gracze_fk FOREIGN KEY ( gracze_gracz_id )
        REFERENCES gracze ( gracz_id );

ALTER TABLE rozgrywki
    ADD CONSTRAINT rozgrywki_gracze_fkv1 FOREIGN KEY ( gracze_gracz_id1 )
        REFERENCES gracze ( gracz_id );

ALTER TABLE rozgrywki
    ADD CONSTRAINT rozgrywki_gry_fk FOREIGN KEY ( gry_tytu³ )
        REFERENCES gry ( tytu³ );

ALTER TABLE rozgrywki
    ADD CONSTRAINT rozgrywki_lokalizacje_fk FOREIGN KEY ( lokalizacje_miasto,
                                                          lokalizacje_obiekt )
        REFERENCES lokalizacje ( miasto,
                                 obiekt );

ALTER TABLE rozgrywki_turniejowe
    ADD CONSTRAINT rozgrywki_turniejowe_kluby_fk FOREIGN KEY ( kluby_nazwa )
        REFERENCES kluby ( nazwa );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE rozgrywki_turniejowe
    ADD CONSTRAINT id_rozgrywka_klub_fkv1 FOREIGN KEY ( kluby_nazwa1 )
        REFERENCES kluby ( nazwa );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE rozgrywki_turniejowe
    ADD CONSTRAINT id_nazwa_turnieju_fk FOREIGN KEY ( turnieje_nazwa )
        REFERENCES turnieje ( nazwa );

ALTER TABLE turnieje
    ADD CONSTRAINT turnieje_lokalizacje_fk FOREIGN KEY ( lokalizacje_miasto,
                                                         lokalizacje_obiekt )
        REFERENCES lokalizacje ( miasto,
                                 obiekt );

ALTER TABLE turnieje
    ADD CONSTRAINT turnieje_wydarzenia_fk FOREIGN KEY ( wydarzenia_nazwa )
        REFERENCES wydarzenia ( nazwa );

ALTER TABLE w³aœciciele_gry
    ADD CONSTRAINT w³aœciciele_gry_gracze_fk FOREIGN KEY ( gracze_imiê,
                                                           gracze_nazwisko )
        REFERENCES gracze ( imiê,
                            nazwisko );

ALTER TABLE w³aœciciele_gry
    ADD CONSTRAINT w³aœciciele_gry_gry_fk FOREIGN KEY ( gry_tytu³ )
        REFERENCES gry ( tytu³ );

ALTER TABLE w³aœciciele_gry
    ADD CONSTRAINT w³aœciciele_gry_kluby_fk FOREIGN KEY ( kluby_nazwa )
        REFERENCES kluby ( nazwa );

CREATE SEQUENCE cz³onek_cz³onek_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER cz³onek_cz³onek_id_trg BEFORE
    INSERT ON cz³onkowie_klubu
    FOR EACH ROW
    WHEN ( new.cz³onek_id IS NULL )
BEGIN
    :new.cz³onek_id := cz³onek_cz³onek_id_seq.nextval;
END;
/

CREATE SEQUENCE gracz_gracz_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER gracz_gracz_id_trg BEFORE
    INSERT ON gracze
    FOR EACH ROW
    WHEN ( new.gracz_id IS NULL )
BEGIN
    :new.gracz_id := gracz_gracz_id_seq.nextval;
END;
/

CREATE SEQUENCE klub_klub_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER klub_klub_id_trg BEFORE
    INSERT ON kluby
    FOR EACH ROW
    WHEN ( new.klub_id IS NULL )
BEGIN
    :new.klub_id := klub_klub_id_seq.nextval;
END;
/

CREATE SEQUENCE rozgrywka_rozgrywka_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER rozgrywka_rozgrywka_id_trg BEFORE
    INSERT ON rozgrywki
    FOR EACH ROW
    WHEN ( new.rozgrywka_id IS NULL )
BEGIN
    :new.rozgrywka_id := rozgrywka_rozgrywka_id_seq.nextval;
END;
/

CREATE SEQUENCE rozgrywka_turniej_rozgrywka_tu START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER rozgrywka_turniej_rozgrywka_tu BEFORE
    INSERT ON rozgrywki_turniejowe
    FOR EACH ROW
    WHEN ( new.rozgrywka_turniej_id IS NULL )
BEGIN
    :new.rozgrywka_turniej_id := rozgrywka_turniej_rozgrywka_tu.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            17
-- CREATE INDEX                             0
-- ALTER TABLE                             46
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           5
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          5
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                  19
-- WARNINGS                                 0
