-- Generated by Oracle SQL Developer Data Modeler 21.2.0.165.1515
--   at:        2021-12-10 20:45:05 CET
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

DROP TABLE autorzy_gry CASCADE CONSTRAINTS;

DROP TABLE czlonkowie_klubu CASCADE CONSTRAINTS;

DROP TABLE dodatki CASCADE CONSTRAINTS;

DROP TABLE gracz_gry_oceny CASCADE CONSTRAINTS;

DROP TABLE gracze CASCADE CONSTRAINTS;

DROP TABLE gry CASCADE CONSTRAINTS;

DROP TABLE kluby CASCADE CONSTRAINTS;

DROP TABLE lokalizacje CASCADE CONSTRAINTS;

DROP TABLE patroni_medialni CASCADE CONSTRAINTS;

DROP TABLE patroni_wydarzenia CASCADE CONSTRAINTS;

DROP TABLE rozgrywka_gracze_role CASCADE CONSTRAINTS;

DROP TABLE rozgrywki CASCADE CONSTRAINTS;

DROP TABLE rozgrywki_turniejowe CASCADE CONSTRAINTS;

DROP TABLE turnieje CASCADE CONSTRAINTS;

DROP TABLE typy_gry CASCADE CONSTRAINTS;

DROP TABLE wlasciciele_gry CASCADE CONSTRAINTS;

DROP TABLE wydarzenia CASCADE CONSTRAINTS;


-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE autorzy_gry (
    imie     VARCHAR2(20 CHAR) NOT NULL,
    nazwisko VARCHAR2(30 CHAR) NOT NULL
);

ALTER TABLE autorzy_gry ADD CONSTRAINT autorzy_gry_pk PRIMARY KEY ( imie,
                                                                    nazwisko );

CREATE TABLE czlonkowie_klubu (
    czlonek_id      NUMBER NOT NULL,
    rola            VARCHAR2(30 CHAR) NOT NULL,
    data_dolaczenia DATE NOT NULL,
    kluby_nazwa     VARCHAR2(50 CHAR) NOT NULL,
    gracze_imie     VARCHAR2(20 CHAR) NOT NULL,
    gracze_nazwisko VARCHAR2(30 CHAR) NOT NULL
);

ALTER TABLE czlonkowie_klubu ADD CONSTRAINT czlonek_pk PRIMARY KEY ( czlonek_id );


ALTER TABLE czlonkowie_klubu ADD CONSTRAINT id_czlonka_klubu UNIQUE ( gracze_imie,
                                                                      gracze_nazwisko );

CREATE TABLE dodatki (
    podtytul  VARCHAR2(30 CHAR) NOT NULL,
    gry_tytul VARCHAR2(30 CHAR) NOT NULL
);

ALTER TABLE dodatki ADD CONSTRAINT dodatki_pk PRIMARY KEY ( podtytul,
                                                            gry_tytul );

CREATE TABLE gracz_gry_oceny (
    ocena           INTEGER NOT NULL,
    gry_tytul       VARCHAR2(30 CHAR) NOT NULL,
    gracze_imie     VARCHAR2(20 CHAR) NOT NULL,
    gracze_nazwisko VARCHAR2(30 CHAR) NOT NULL,
    gracze_gracz_id NUMBER NOT NULL
);

ALTER TABLE gracz_gry_oceny
    ADD CONSTRAINT gracz_gry_oceny_pk PRIMARY KEY ( ocena,
                                                    gracze_imie,
                                                    gracze_nazwisko,
                                                    gry_tytul );

CREATE TABLE gracze (
    gracz_id NUMBER NOT NULL,
    imie     VARCHAR2(20 CHAR) NOT NULL,
    nazwisko VARCHAR2(30 CHAR) NOT NULL
);

ALTER TABLE gracze ADD CONSTRAINT gracz_pk PRIMARY KEY ( gracz_id );

ALTER TABLE gracze ADD CONSTRAINT gracze_imie_nazwisko_un UNIQUE ( imie,
                                                                   nazwisko );

CREATE TABLE gry (
    tytul                VARCHAR2(30 CHAR) NOT NULL,
    autorzy_gry_imie     VARCHAR2(20 CHAR) NOT NULL,
    autorzy_gry_nazwisko VARCHAR2(30 CHAR) NOT NULL,
    typy_gry_gatunek     VARCHAR2(20 CHAR) NOT NULL
);

ALTER TABLE gry ADD CONSTRAINT gry_pk PRIMARY KEY ( tytul );

CREATE TABLE kluby (
    klub_id NUMBER NOT NULL,
    nazwa   VARCHAR2(50 CHAR) NOT NULL
);

ALTER TABLE kluby ADD CONSTRAINT klub_pk PRIMARY KEY ( klub_id );

ALTER TABLE kluby ADD CONSTRAINT kluby_nazwa_un UNIQUE ( nazwa );

CREATE TABLE lokalizacje (
    miasto VARCHAR2(30 CHAR) NOT NULL,
    obiekt VARCHAR2(30 CHAR) NOT NULL
);

ALTER TABLE lokalizacje ADD CONSTRAINT lokalizacje_pk PRIMARY KEY ( miasto,
                                                                    obiekt );

CREATE TABLE patroni_medialni (
    nazwa VARCHAR2(50 CHAR) NOT NULL
);

ALTER TABLE patroni_medialni ADD CONSTRAINT patroni_medialni_pk PRIMARY KEY ( nazwa );

CREATE TABLE patroni_wydarzenia (
    wydarzenia_nazwa       VARCHAR2(30 CHAR) NOT NULL,
    patroni_medialni_nazwa VARCHAR2(50 CHAR) NOT NULL
);

ALTER TABLE patroni_wydarzenia ADD CONSTRAINT patroni_wydarzen PRIMARY KEY ( wydarzenia_nazwa,
                                                                             patroni_medialni_nazwa );

CREATE TABLE rozgrywka_gracze_role (
    rola                                      VARCHAR2(30 CHAR) NOT NULL,
    nazwa                                     VARCHAR2(30 CHAR) NOT NULL,
    imie_gracza                               VARCHAR2(20 CHAR) NOT NULL, 
    nazwisko_gracza                           VARCHAR2(30 CHAR) NOT NULL,
    nazwa_klubu_1                             VARCHAR2(50 CHAR) NOT NULL,
    nazwa_klubu_2                             VARCHAR2(50 CHAR) NOT NULL,
    data                                      DATE NOT NULL, 
    id_rozgrywki_turniejowej                  NUMBER NOT NULL,
    nazwa_turnieju                            VARCHAR2(30 CHAR) NOT NULL,
    czlonkowie_klubu_czlonek_id               NUMBER NOT NULL
);

ALTER TABLE rozgrywka_gracze_role
    ADD CONSTRAINT rozgrywka_gracze_role_pk PRIMARY KEY ( nazwa,
                                                          nazwa_klubu_1,
                                                          nazwa_klubu_2,
                                                          data,
                                                          rola,
                                                          imie_gracza,
                                                          nazwisko_gracza );

CREATE TABLE rozgrywki (
    rozgrywka_id       NUMBER NOT NULL,
    data               DATE NOT NULL,
    wygrywajacy_gracz  CHAR(50 CHAR),
    gry_tytul          VARCHAR2(30 CHAR) NOT NULL,
    gracze_imie        VARCHAR2(20 CHAR) NOT NULL,
    gracze_nazwisko    VARCHAR2(30 CHAR) NOT NULL,
    gracze_imie1       VARCHAR2(20 CHAR) NOT NULL,
    gracze_nazwisko1   VARCHAR2(30 CHAR) NOT NULL,
    lokalizacje_miasto VARCHAR2(30 CHAR) NOT NULL,
    lokalizacje_obiekt VARCHAR2(30 CHAR) NOT NULL,
    gracze_gracz_id    NUMBER NOT NULL,
    gracze_gracz_id1   NUMBER NOT NULL
);

ALTER TABLE rozgrywki ADD CONSTRAINT rozgrywka_pk PRIMARY KEY ( rozgrywka_id );


ALTER TABLE rozgrywki
    ADD CONSTRAINT id_rozgrywki UNIQUE ( gry_tytul,
                                         gracze_imie1,
                                         gracze_nazwisko1,
                                         gracze_imie,
                                         gracze_nazwisko,
                                         data );

CREATE TABLE rozgrywki_turniejowe (
    rozgrywka_turniej_id NUMBER NOT NULL,
    data                 DATE NOT NULL,
    wygrywajacy_klub     VARCHAR2(50 CHAR),
    kluby_nazwa          VARCHAR2(50 CHAR) NOT NULL,
    kluby_nazwa1         VARCHAR2(50 CHAR) NOT NULL,
    turnieje_nazwa       VARCHAR2(30 CHAR) NOT NULL,
    kluby_klub_id        NUMBER NOT NULL,
    kluby_klub_id1       NUMBER NOT NULL
);

ALTER TABLE rozgrywki_turniejowe ADD CONSTRAINT rozgrywka_turniej_pk PRIMARY KEY ( rozgrywka_turniej_id );


ALTER TABLE rozgrywki_turniejowe
    ADD CONSTRAINT id_rozgrywki_turniejowej UNIQUE ( turnieje_nazwa,
                                                     kluby_nazwa,
                                                     kluby_nazwa1,
                                                     data );

CREATE TABLE turnieje (
    nazwa              VARCHAR2(30 CHAR) NOT NULL,
    wydarzenia_nazwa   VARCHAR2(30 CHAR) NOT NULL,
    lokalizacje_miasto VARCHAR2(30 CHAR) NOT NULL,
    lokalizacje_obiekt VARCHAR2(30 CHAR) NOT NULL
);

ALTER TABLE turnieje ADD CONSTRAINT turnieje_pk PRIMARY KEY ( nazwa );

CREATE TABLE typy_gry (
    gatunek           VARCHAR2(20 CHAR) NOT NULL,
    gatunek_dodatkowy VARCHAR2(20 CHAR)
);

ALTER TABLE typy_gry ADD CONSTRAINT typy_gry_pk PRIMARY KEY ( gatunek );

CREATE TABLE wlasciciele_gry (
    gracze_imie     VARCHAR2(20 CHAR),
    gracze_nazwisko VARCHAR2(30 CHAR),
    kluby_nazwa     VARCHAR2(50 CHAR),
    gry_tytul       VARCHAR2(30 CHAR) NOT NULL,
    koszt_zakupu    FLOAT
);

ALTER TABLE wlasciciele_gry
    ADD CONSTRAINT arc_1 CHECK ( ( ( gracze_imie IS NOT NULL )
                                   AND ( gracze_nazwisko IS NOT NULL )
                                   AND ( kluby_nazwa IS NULL ) )
                                 OR ( ( kluby_nazwa IS NOT NULL )
                                      AND ( gracze_imie IS NULL )
                                      AND ( gracze_nazwisko IS NULL ) ) );

ALTER TABLE wlasciciele_gry ADD CONSTRAINT wlasciciele_gry_pk PRIMARY KEY ( gry_tytul );

CREATE TABLE wydarzenia (
    nazwa       VARCHAR2(30 CHAR) NOT NULL,
    organizator VARCHAR2(50 CHAR) NOT NULL
);

ALTER TABLE wydarzenia ADD CONSTRAINT wydarzenia_pk PRIMARY KEY ( nazwa );

ALTER TABLE czlonkowie_klubu
    ADD CONSTRAINT czlonkowie_klubu_gracze_fk FOREIGN KEY ( gracze_imie,
                                                            gracze_nazwisko )
        REFERENCES gracze ( imie,
                            nazwisko );

ALTER TABLE czlonkowie_klubu
    ADD CONSTRAINT czlonkowie_klubu_kluby_fk FOREIGN KEY ( kluby_nazwa )
        REFERENCES kluby ( nazwa );

ALTER TABLE dodatki
    ADD CONSTRAINT dodatki_gry_fk FOREIGN KEY ( gry_tytul )
        REFERENCES gry ( tytul );

ALTER TABLE gracz_gry_oceny
    ADD CONSTRAINT gracz_gry_oceny_gracze_fk FOREIGN KEY ( gracze_gracz_id )
        REFERENCES gracze (gracz_id );

ALTER TABLE gracz_gry_oceny
    ADD CONSTRAINT gracz_gry_oceny_gry_fk FOREIGN KEY ( gry_tytul )
        REFERENCES gry ( tytul );

ALTER TABLE gry
    ADD CONSTRAINT gry_autorzy_gry_fk FOREIGN KEY ( autorzy_gry_imie,
                                                    autorzy_gry_nazwisko )
        REFERENCES autorzy_gry ( imie,
                                 nazwisko );

ALTER TABLE gry
    ADD CONSTRAINT gry_typy_gry_fk FOREIGN KEY ( typy_gry_gatunek )
        REFERENCES typy_gry ( gatunek );

ALTER TABLE patroni_wydarzenia
    ADD CONSTRAINT id_patrona_fk FOREIGN KEY ( patroni_medialni_nazwa )
        REFERENCES patroni_medialni ( nazwa );

ALTER TABLE patroni_wydarzenia
    ADD CONSTRAINT patroni_wydarzen_wydarzenia_fk FOREIGN KEY ( wydarzenia_nazwa )
        REFERENCES wydarzenia ( nazwa );

ALTER TABLE rozgrywka_gracze_role
    ADD CONSTRAINT id_roli_gracza_fk FOREIGN KEY ( czlonkowie_klubu_czlonek_id )
        REFERENCES czlonkowie_klubu ( czlonek_id );

ALTER TABLE rozgrywka_gracze_role
    ADD CONSTRAINT id_rola_rozgrywka_fk FOREIGN KEY ( id_rozgrywki_turniejowej )
        REFERENCES rozgrywki_turniejowe ( rozgrywka_turniej_id );

ALTER TABLE rozgrywki
    ADD CONSTRAINT rozgrywki_gracze_fk FOREIGN KEY ( gracze_gracz_id )
        REFERENCES gracze ( gracz_id );

ALTER TABLE rozgrywki
    ADD CONSTRAINT rozgrywki_gracze_fkv1 FOREIGN KEY ( gracze_gracz_id1 )
        REFERENCES gracze ( gracz_id );

ALTER TABLE rozgrywki
    ADD CONSTRAINT rozgrywki_gry_fk FOREIGN KEY ( gry_tytul )
        REFERENCES gry ( tytul );

ALTER TABLE rozgrywki
    ADD CONSTRAINT rozgrywki_lokalizacje_fk FOREIGN KEY ( lokalizacje_miasto,
                                                          lokalizacje_obiekt )
        REFERENCES lokalizacje ( miasto,
                                 obiekt );

ALTER TABLE rozgrywki_turniejowe
    ADD CONSTRAINT rozgrywki_turniejowe_kluby_fk FOREIGN KEY ( kluby_nazwa )
        REFERENCES kluby ( nazwa );

ALTER TABLE rozgrywki_turniejowe
    ADD CONSTRAINT id_rozgrywka_klub_fkv1 FOREIGN KEY ( kluby_nazwa1 )
        REFERENCES kluby ( nazwa );

ALTER TABLE rozgrywki_turniejowe
    ADD CONSTRAINT id_nazwa_turnieju_fk FOREIGN KEY ( turnieje_nazwa )
        REFERENCES turnieje ( nazwa );

ALTER TABLE turnieje
    ADD CONSTRAINT turnieje_lokalizacje_fk FOREIGN KEY ( lokalizacje_miasto,
                                                         lokalizacje_obiekt )
        REFERENCES lokalizacje ( miasto,
                                 obiekt );

ALTER TABLE turnieje
    ADD CONSTRAINT turnieje_wydarzenia_fk FOREIGN KEY ( wydarzenia_nazwa )
        REFERENCES wydarzenia ( nazwa );

ALTER TABLE wlasciciele_gry
    ADD CONSTRAINT wlasciciele_gry_gracze_fk FOREIGN KEY ( gracze_imie,
                                                           gracze_nazwisko )
        REFERENCES gracze ( imie,
                            nazwisko );

ALTER TABLE wlasciciele_gry
    ADD CONSTRAINT wlasciciele_gry_gry_fk FOREIGN KEY ( gry_tytul )
        REFERENCES gry ( tytul );

ALTER TABLE wlasciciele_gry
    ADD CONSTRAINT wlasciciele_gry_kluby_fk FOREIGN KEY ( kluby_nazwa )
        REFERENCES kluby ( nazwa );

CREATE SEQUENCE czlonek_czlonek_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER czlonek_czlonek_id_trg BEFORE
    INSERT ON czlonkowie_klubu
    FOR EACH ROW
    WHEN ( new.czlonek_id IS NULL )
BEGIN
    :new.czlonek_id := czlonek_czlonek_id_seq.nextval;
END;
/

CREATE SEQUENCE gracz_gracz_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER gracz_gracz_id_trg BEFORE
    INSERT ON gracze
    FOR EACH ROW
    WHEN ( new.gracz_id IS NULL )
BEGIN
    :new.gracz_id := gracz_gracz_id_seq.nextval;
END;
/

CREATE SEQUENCE klub_klub_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER klub_klub_id_trg BEFORE
    INSERT ON kluby
    FOR EACH ROW
    WHEN ( new.klub_id IS NULL )
BEGIN
    :new.klub_id := klub_klub_id_seq.nextval;
END;
/

CREATE SEQUENCE rozgrywka_rozgrywka_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER rozgrywka_rozgrywka_id_trg BEFORE
    INSERT ON rozgrywki
    FOR EACH ROW
    WHEN ( new.rozgrywka_id IS NULL )
BEGIN
    :new.rozgrywka_id := rozgrywka_rozgrywka_id_seq.nextval;
END;
/

CREATE SEQUENCE rozgrywka_turniej_rozgrywka_tu START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER rozgrywka_turniej_rozgrywka_tu BEFORE
    INSERT ON rozgrywki_turniejowe
    FOR EACH ROW
    WHEN ( new.rozgrywka_turniej_id IS NULL )
BEGIN
    :new.rozgrywka_turniej_id := rozgrywka_turniej_rozgrywka_tu.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            17
-- CREATE INDEX                             0
-- ALTER TABLE                             46
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           5
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          5
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                         17
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
